### ISSUE TITLE
Playlist issue

### ISSUE THREAD

**Issue by halibegic** [mangui/flashls#271]
When the next video is played, in playlist, it shows only black screen and I hear the audio. (Flash version  17,0,0,169)

Demo: http://halibegic.info/ms/playlist/

**Comment by blacktrash** [comment]
Duplicate of https://github.com/mangui/flashls/issues/157 I'd say.

**Comment by mangui** [comment]
@halibegic 
as I pushed a potential fix for #157, it would be worth rechecking this issue with latest flashls/dev
thanks,
Mangui

**Comment by halibegic** [comment]
I downloaded the latest .swf from https://github.com/mangui/flashls/blob/dev/bin/release/flashlsFlowPlayer.swf but issue is still present.
Can this issue be related with the clip alpha because I found this inside the console log
```[LOG] time 22:48:25.664 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0```

**Comment by mangui** [comment]
indeed it is quite strange, alpha is decreasing ?
````
"[LOG] time 23:11:04.977 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 1" playlist
"[LOG] time 23:11:05.28 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.765625" playlist
"[LOG] time 23:11:05.64 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.62890625" playlist
"[LOG] time 23:11:05.103 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.50390625" playlist
"[LOG] time 23:11:05.136 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.41796875" playlist
"[LOG] time 23:11:05.169 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.33984375" playlist
"[LOG] time 23:11:05.201 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.27734375" playlist
"[LOG] time 23:11:05.232 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.2265625" playlist
"[LOG] time 23:11:05.263 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.18359375" playlist
"[LOG] time 23:11:05.297 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.14453125" playlist
"[LOG] time 23:11:05.331 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.109375" playlist
"[LOG] time 23:11:05.367 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.08203125" playlist
"[LOG] time 23:11:05.398 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.0625" playlist
"[LOG] time 23:11:05.435 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.04296875" playlist
"[LOG] time 23:11:05.466 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.03125" playlist
"[LOG] time 23:11:05.498 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.0234375" playlist
"[LOG] time 23:11:05.534 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.015625" playlist
"[LOG] time 23:11:05.564 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.01171875" playlist
"[LOG] time 23:11:05.596 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.0078125" playlist
"[LOG] time 23:11:05.629 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0.00390625" playlist
"[LOG] time 23:11:05.659 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.683 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.708 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.734 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.771 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.794 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.818 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.848 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.878 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.912 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.940 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:05.975 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
"[LOG] time 23:11:06.17 :: org.flowplayer.view::VideoDisplay : display of + [Clip] 'http://www.streambox.fr/playlists/test_001/stream.m3u8' new alpha 0" playlist
````

**Comment by halibegic** [comment]
Yes, before playing second video.

**Comment by mangui** [comment]
all these calls happens in less than 2s.
this is triggered from here : https://github.com/flowplayer/flash/blob/1caea54d3e7fa66b6496d556998052507a6d05a4/core/src/actionscript/org/flowplayer/view/VideoDisplay.as#L62
I dont know which part of FlowPlayer is triggering this ...

**Comment by mangui** [comment]
duplicate with #157
