### ISSUE TITLE
Error #2123 when trying to draw the video to a BitmapData object

### ISSUE THREAD

**Issue by oripessach** [mangui/flashls#273]
I tried modifying  ChromelessPlayer.as to add the ability to obtain a Base64 encoded screenshot of the currently playing video, and I'm getting an error #2123 on code similar to this:

var screenshot: BitmapData = new BitmapData(_video.videoWidth, _video.videoHeight);
screenshot.draw(_video); // Exception is thrown here

The video source is different from the server that the swf file is downloaded from. Researching this, it looks like I would have to create a LoaderContext object, set its checkPolicyFile to true, and then pass it to the Loader object used to download the video... Except that there is no loader object being used - FragmentLoader.as seems to use a URLStream, instead, and I don't see a way to set a LoaderContext for that.

Is there a way to modify the code to allow rendering a video to a BitmapData object, or is there another way to (quickly) obtain a screenshot of the playing video?

**Comment by minoscc** [comment]
red5 or fms?
You must set the permissions on the server.
BitmapData cant direct catch the video stream.

**Comment by mangui** [comment]
never experimented with this, maybe this could help ?
http://gamespoweredby.com/blog/2014/11/netstream-playnull-bitmapdata-workaround/

**Comment by minoscc** [comment]
@mangui oh~ye~, it also help me, thanks. :smile:

**Comment by mangui** [comment]
@minoscc did you mean you manage to make a bitmap capture thanks to my link ?

**Comment by minoscc** [comment]
@mangui yes, I've wanted to do it before a few months, but did not succeed.

**Comment by oripessach** [comment]
I'm having difficulties applying the technique described in that link. Specifically, I can't seem to call or otherwise access this.graphics.readGraphicsData() (in ChromelessPlayer.as) - I believe that should be available, since ChromelessPlayer is derived from Sprite, and Sprite has a graphics member of type Graphics, and Graphics has a readGraphicsData() method... Except that it doesn't, according to the runtime - even trying to do:

Log.info(typeof(super.graphics.readGraphicsData));

Throws an exception (ReferenceError - #1069.)

I'm using Air, by the way. I was having different issues when trying to compile with Flex. 

Any ideas what might be going on here?

**Comment by oripessach** [comment]
I figured it out. The target player need to be set to 11.6 - the earliest version that supports readGraphicsData(). Basically, everywhere in the build script that mentions the target player version needed to be changed to -target-player="11.6".

**Comment by mangui** [comment]
resolved using target player 11.6

**Comment by dviramontes** [comment]
@oripessach would you care to share where you make this call to `super.graphics.readGraphicsData()`
in your code. I got something like this going for **_ChromelessPlayer.as**_. 

```
protected function _getScreenshotBytes() : String {
    var screenshotData:BitmapData;
    Log.info(typeof(super.graphics.readGraphicsData)); // returns 'function' yay!
    var graphicsData:Vector.<IGraphicsData> = super.graphics.readGraphicsData();
    if (graphicsData.length > 0) {
        screenshotData = GraphicsBitmapFill(graphicsData[1]).bitmapData;  // <== type error
    }
    var png:ByteArray = new PNGEncoder().encode(screenshotData);
    var encoder:Base64Encoder = new Base64Encoder();
    encoder.encodeBytes(png);
    return encoder.toString();
};
```

but its throwing a type error, **Uncaught TypeError: Error #1034**

**Comment by dviramontes** [comment]
I tried to build with flash **11.4** and **16.0** (latest as of Sept 2015) and I still see
**Error #2123: Securty error** when I call

```
screenshot.draw(_video);
```

@mangui @oripessach @minoscc
any other tips you can share ?

**Comment by turbidwater** [comment]
If you're getting a security error, it usually means the stream doesn't allow bitmap access. That is usually a server setting. If you are using AMS (FMS) you usually need to say that the client can access video sample data on the server side: https://helpx.adobe.com/adobe-media-server/ssaslr/client-class.html#client_videosampleaccess

**Comment by dviramontes** [comment]
Not using AMS here.
I've also tried adding a permissive **_crossdomain.xml**_ file but no luck :/

**Comment by minosss** [comment]
try this~

```
if ( graphicsData.length > 0 ) {
  bitmap.bitmapData = GraphicsBitmapFill( graphicsData[0] ).bitmapData; // << [0]
}
```

**Comment by vishhin** [comment]
Hi, 
I changed my target player version to 11.6 as suggested by @oripessach and yet I face the same readGraphicsData-undefined issue. My compiler option looks like this: 

-locale en_US -debug=true -define+=CONFIG::LOGGING,false -target-player="11.6" -swf-version=19 -define+=CONFIG::FLASH_10_1,false

Is there anything wrong with the syntax? I'm new to flash. What all should I check to read all graphics data and drawing it into a bitmap?
