### ISSUE TITLE
Artifacts when playing back DVR stream with uneven fragments duration with OSMF player

### ISSUE THREAD

**Issue by rwlodkowski** [mangui/flashls#454]
Hey @mangui,

here is my test stream:
http://flashls.wlodkowski.net/osmf/GrindPlayer_dvrtest2.html

here is the screening:
https://youtu.be/DmnWznbew-Y

and full debug log:
https://www.dropbox.com/s/ljbv5m67abdgphf/debuglog.txt?dl=0

It's an live stream with uneven fragments - mixed 10s and 19s durations. I'm not sure if it's the main cause of the problems with it but probably it's something worth mentioning.

The other issues with this stream are with seeking to live position:
- when you seek to the end of it, then the steam after some time in buffering state is stopped and reset (probably it's also related with #453)
- sometimes the offset of live position is too big when the stream is starting to play or is seeked to live position with API call. With SMP you can use snapToLive().

What's interesting I'm not experiencing this issues with chromeless player.

Let me know if I should create separate issues for all of the problems with this stream.

Btw. I'm quite sure that the artifact and freezing/reset issue was introduced with v0.4.4.13 and it's related with "overlapping fragments". It's not only appearing with live playlists but with VOD playlists also I'll provide follow up info about that later.

**Comment by mangui** [comment]
Are you checking with v0.4.4.15 ? There are issues with 0.4.4.13 and 0.4.4.14

**Comment by rwlodkowski** [comment]
Yes. I'm describing issues with lastest release: v0.4.4.15.

**Comment by mangui** [comment]
could you check with v0.4.4.11 and let me know if you can repro ?

**Comment by mangui** [comment]
plz recheck with latest flashls/dev, issue should be fixed

**Comment by rwlodkowski** [comment]
I confirm that there are less artifacts, but they are still present (especially green freeze screens).  Issues with seeking to live are still there.

**Comment by mangui** [comment]
did you check with latest swf (v0.4.4.16) ?

**Comment by rwlodkowski** [comment]
OK I've rechecked it and everything fine with v0.4.4.16. Thank you. Closing.
